---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    component: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mongo
  template:
    metadata:
      name: mongo
      labels:
        component: mongo
    spec:
      containers:
      - image: mongo:3.2
        name: mongo

