---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "post.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: searcher.{{ .Values.baseDomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "post.fullname" . }}
          servicePort: {{ .Values.service.externalPort }}

