version: '3.3'
services:
  db:
    image: mongo
    networks:
      - searcher

  mq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}
      RABBITMQ_DEFAULT_VHOST: "/"
    networks:
      - searcher

  crawler:
    build: ./search_engine_crawler-master 
    image: crowler:${CRAWLER_VER}
    depends_on:
      - db
      - mq
    restart: on-failure
    environment:
      MONGO: "db"
      RMQ_HOST: "mq"
      RMQ_USERNAME: ${RABBIT_USER}
      RMQ_PASSWORD: ${RABBIT_PASS}
      EXCLUDE_URLS: ".*github.com"
    ports:
      - "8000:8000"
    networks:
      - searcher

  ui:
    build: ./search_engine_ui-master
    image: searcher-ui:${UI_VER}
    depends_on:
      - db
    environment:
      MONGO: "db"
    ports:
      - "8001:8000"
    networks:
      - searcher

networks:
  searcher:

