version: '3.3'
services:
  db:
    image: mongo
    networks:
      - searcher

  mq:
    image: "rabbitmq:3-management"
    environment:
      #RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}
      RABBITMQ_DEFAULT_VHOST: "/"
      #    ports:
      #      - "15672:15672"
      #      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
   #volumes:
      #- "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
    networks:
      - searcher

  crawler:
    build: ./search_engine_crawler-master 
    image: crowler:${CRAWLER_VER}
    #command: sh -c "sleep 10 && python3 -u crawler/crawler.py https://vitkhab.github.io/search_engine_test_site/"
    depends_on:
      - db
      - mq
    restart: on-failure
    #command: "sleep 10000"
    environment:
      MONGO: "db"
      RMQ_HOST: "mq"
      RMQ_USERNAME: ${RABBIT_USER}
      RMQ_PASSWORD: ${RABBIT_PASS}
      EXCLUDE_URLS: ".*github.com"
    ports:
      - "8000:8000"
    networks:
      - searcher

  ui:
    build: ./search_engine_ui-master
    image: searcher-ui:${UI_VER}
    #command: "sleep 10000"
    depends_on:
      - db
    environment:
      MONGO: "db"
    ports:
      - "8001:8000"
    networks:
      - searcher

networks:
  searcher:

