---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: otus-project
    component: crawler
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otus-project
      component: crawler
      release: {{ .Release.Name }}
  template:
    metadata:
      name: crawler
      labels:
        app: otus-project
        component: crawler
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: crawler
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: searcher
          protocol: TCP
        env:
        - name: MONGO
          value: "mongodb"
        - name: RMQ_HOST
          value: "rabbitmq"
        - name: RMQ_USERNAME
          value: "rabbitmq"
        - name: RMQ_PASSWORD
          value: "rabbitmq"
        - name: EXCLUDE_URLS
          value: ".*github.com"

