---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "post.fullname" . }}
  labels:
    app: otus-project
    component: crawler
    release: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: otus-project
    component: crawler
    release: {{ .Release.Name }}

